# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(890, 592)
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/Images/Matrix Calc.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 0, 512, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.openBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.openBtn.setObjectName("openBtn")
        self.horizontalLayout.addWidget(self.openBtn)
        self.saveBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.saveBtn.setFont(font)
        self.saveBtn.setObjectName("saveBtn")
        self.horizontalLayout.addWidget(self.saveBtn)
        self.clearBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.clearBtn.setFont(font)
        self.clearBtn.setObjectName("clearBtn")
        self.horizontalLayout.addWidget(self.clearBtn)
        self.manualBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.manualBtn.setFont(font)
        self.manualBtn.setObjectName("manualBtn")
        self.horizontalLayout.addWidget(self.manualBtn)
        self.aboutBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.aboutBtn.setFont(font)
        self.aboutBtn.setObjectName("aboutBtn")
        self.horizontalLayout.addWidget(self.aboutBtn)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(544, 29, 351, 521))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.resultsEntry = QtWidgets.QPlainTextEdit(self.groupBox_3)
        self.resultsEntry.setGeometry(QtCore.QRect(0, 20, 351, 501))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.resultsEntry.sizePolicy().hasHeightForWidth())
        self.resultsEntry.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStrikeOut(False)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.resultsEntry.setFont(font)
        self.resultsEntry.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.resultsEntry.setAutoFillBackground(False)
        self.resultsEntry.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.resultsEntry.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.resultsEntry.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.resultsEntry.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.resultsEntry.setReadOnly(True)
        self.resultsEntry.setOverwriteMode(False)
        self.resultsEntry.setTabStopWidth(80)
        self.resultsEntry.setCursorWidth(1)
        self.resultsEntry.setMaximumBlockCount(0)
        self.resultsEntry.setBackgroundVisible(False)
        self.resultsEntry.setCenterOnScroll(False)
        self.resultsEntry.setObjectName("resultsEntry")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(1, 11, 266, 541))
        self.frame.setObjectName("frame")
        self.groupBox_4 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_4.setGeometry(QtCore.QRect(1, 21, 259, 181))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.matAEntry = QtWidgets.QPlainTextEdit(self.groupBox_4)
        self.matAEntry.setGeometry(QtCore.QRect(0, 20, 251, 161))
        self.matAEntry.setObjectName("matAEntry")
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_5.setGeometry(QtCore.QRect(1, 210, 259, 191))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.matBEntry = QtWidgets.QPlainTextEdit(self.groupBox_5)
        self.matBEntry.setGeometry(QtCore.QRect(3, 19, 251, 171))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.matBEntry.setFont(font)
        self.matBEntry.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.matBEntry.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.matBEntry.setAutoFillBackground(False)
        self.matBEntry.setTabChangesFocus(False)
        self.matBEntry.setOverwriteMode(True)
        self.matBEntry.setTabStopWidth(80)
        self.matBEntry.setBackgroundVisible(False)
        self.matBEntry.setCenterOnScroll(False)
        self.matBEntry.setObjectName("matBEntry")
        self.swapBtn = QtWidgets.QToolButton(self.groupBox_5)
        self.swapBtn.setGeometry(QtCore.QRect(110, 0, 61, 21))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.swapBtn.setFont(font)
        self.swapBtn.setObjectName("swapBtn")
        self.groupBox_6 = QtWidgets.QGroupBox(self.frame)
        self.groupBox_6.setGeometry(QtCore.QRect(1, 400, 261, 151))
        self.groupBox_6.setTitle("")
        self.groupBox_6.setObjectName("groupBox_6")
        self.frame_8 = QtWidgets.QFrame(self.groupBox_6)
        self.frame_8.setGeometry(QtCore.QRect(4, 18, 251, 121))
        self.frame_8.setObjectName("frame_8")
        self.groupBox_9 = QtWidgets.QGroupBox(self.frame_8)
        self.groupBox_9.setGeometry(QtCore.QRect(10, 10, 241, 41))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.x_val = QtWidgets.QLineEdit(self.groupBox_9)
        self.x_val.setGeometry(QtCore.QRect(0, 20, 241, 21))
        self.x_val.setInputMethodHints(QtCore.Qt.ImhNone)
        self.x_val.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.x_val.setDragEnabled(False)
        self.x_val.setReadOnly(False)
        self.x_val.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.x_val.setClearButtonEnabled(False)
        self.x_val.setObjectName("x_val")
        self.groupBox_10 = QtWidgets.QGroupBox(self.frame_8)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 60, 241, 51))
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.precisionVal = QtWidgets.QComboBox(self.groupBox_10)
        self.precisionVal.setGeometry(QtCore.QRect(0, 20, 241, 31))
        self.precisionVal.setEditable(True)
        self.precisionVal.setObjectName("precisionVal")
        self.precisionVal.addItem("")
        self.precisionVal.addItem("")
        self.precisionVal.addItem("")
        self.precisionVal.addItem("")
        self.precisionVal.addItem("")
        self.precisionVal.addItem("")
        self.precisionVal.addItem("")
        self.precisionVal.addItem("")
        self.precisionVal.addItem("")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(273, 19, 265, 531))
        self.frame_2.setObjectName("frame_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame_2)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 20, 261, 521))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.arrMulAB = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.arrMulAB.setFont(font)
        self.arrMulAB.setObjectName("arrMulAB")
        self.gridLayout.addWidget(self.arrMulAB, 4, 2, 1, 1)
        self.minB = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.minB.setFont(font)
        self.minB.setObjectName("minB")
        self.gridLayout.addWidget(self.minB, 5, 1, 1, 1)
        self.invA = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.invA.setFont(font)
        self.invA.setObjectName("invA")
        self.gridLayout.addWidget(self.invA, 3, 0, 1, 1)
        self.detB = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.detB.setFont(font)
        self.detB.setObjectName("detB")
        self.gridLayout.addWidget(self.detB, 9, 1, 1, 1)
        self.addMatAB = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.addMatAB.setFont(font)
        self.addMatAB.setObjectName("addMatAB")
        self.gridLayout.addWidget(self.addMatAB, 1, 2, 1, 1)
        self.arrdivmatAB = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.arrdivmatAB.setFont(font)
        self.arrdivmatAB.setObjectName("arrdivmatAB")
        self.gridLayout.addWidget(self.arrdivmatAB, 6, 2, 1, 1)
        self.luA = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.luA.setFont(font)
        self.luA.setObjectName("luA")
        self.gridLayout.addWidget(self.luA, 13, 0, 1, 1)
        self.svdB = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.svdB.setFont(font)
        self.svdB.setObjectName("svdB")
        self.gridLayout.addWidget(self.svdB, 15, 1, 1, 1)
        self.cholB = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.cholB.setFont(font)
        self.cholB.setObjectName("cholB")
        self.gridLayout.addWidget(self.cholB, 14, 1, 1, 1)
        self.matApowx = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.matApowx.setFont(font)
        self.matApowx.setObjectName("matApowx")
        self.gridLayout.addWidget(self.matApowx, 12, 2, 1, 1)
        self.logicalXOR = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.logicalXOR.setFont(font)
        self.logicalXOR.setObjectName("logicalXOR")
        self.gridLayout.addWidget(self.logicalXOR, 9, 2, 1, 1)
        self.rankB = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.rankB.setFont(font)
        self.rankB.setObjectName("rankB")
        self.gridLayout.addWidget(self.rankB, 10, 1, 1, 1)
        self.luB = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.luB.setFont(font)
        self.luB.setObjectName("luB")
        self.gridLayout.addWidget(self.luB, 13, 1, 1, 1)
        self.eigB = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.eigB.setFont(font)
        self.eigB.setObjectName("eigB")
        self.gridLayout.addWidget(self.eigB, 11, 1, 1, 1)
        self.qrB = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.qrB.setFont(font)
        self.qrB.setObjectName("qrB")
        self.gridLayout.addWidget(self.qrB, 12, 1, 1, 1)
        self.autoBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.autoBtn.setMinimumSize(QtCore.QSize(60, 53))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(True)
        font.setUnderline(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.autoBtn.setFont(font)
        self.autoBtn.setAutoFillBackground(False)
        self.autoBtn.setObjectName("autoBtn")
        self.gridLayout.addWidget(self.autoBtn, 14, 2, 2, 1)
        self.matAmulx = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.matAmulx.setFont(font)
        self.matAmulx.setObjectName("matAmulx")
        self.gridLayout.addWidget(self.matAmulx, 10, 2, 1, 1)
        self.normB = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.normB.setFont(font)
        self.normB.setObjectName("normB")
        self.gridLayout.addWidget(self.normB, 6, 1, 1, 1)
        self.logicalOR = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.logicalOR.setFont(font)
        self.logicalOR.setObjectName("logicalOR")
        self.gridLayout.addWidget(self.logicalOR, 8, 2, 1, 1)
        self.proAB = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.proAB.setFont(font)
        self.proAB.setObjectName("proAB")
        self.gridLayout.addWidget(self.proAB, 3, 2, 1, 1)
        self.dimB = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.dimB.setFont(font)
        self.dimB.setObjectName("dimB")
        self.gridLayout.addWidget(self.dimB, 7, 1, 1, 1)
        self.logicalAND = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.logicalAND.setFont(font)
        self.logicalAND.setObjectName("logicalAND")
        self.gridLayout.addWidget(self.logicalAND, 7, 2, 1, 1)
        self.dimA = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.dimA.setFont(font)
        self.dimA.setObjectName("dimA")
        self.gridLayout.addWidget(self.dimA, 7, 0, 1, 1)
        self.invB = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.invB.setFont(font)
        self.invB.setObjectName("invB")
        self.gridLayout.addWidget(self.invB, 3, 1, 1, 1)
        self.transA = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.transA.setFont(font)
        self.transA.setObjectName("transA")
        self.gridLayout.addWidget(self.transA, 2, 0, 1, 1)
        self.maxA = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.maxA.setFont(font)
        self.maxA.setObjectName("maxA")
        self.gridLayout.addWidget(self.maxA, 4, 0, 1, 1)
        self.traceA = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.traceA.setFont(font)
        self.traceA.setObjectName("traceA")
        self.gridLayout.addWidget(self.traceA, 8, 0, 1, 1)
        self.detA = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.detA.setFont(font)
        self.detA.setObjectName("detA")
        self.gridLayout.addWidget(self.detA, 9, 0, 1, 1)
        self.minA = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.minA.setFont(font)
        self.minA.setObjectName("minA")
        self.gridLayout.addWidget(self.minA, 5, 0, 1, 1)
        self.matB = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.matB.setFont(font)
        self.matB.setObjectName("matB")
        self.gridLayout.addWidget(self.matB, 1, 1, 1, 1)
        self.divmatAB = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.divmatAB.setFont(font)
        self.divmatAB.setObjectName("divmatAB")
        self.gridLayout.addWidget(self.divmatAB, 5, 2, 1, 1)
        self.transB = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.transB.setFont(font)
        self.transB.setObjectName("transB")
        self.gridLayout.addWidget(self.transB, 2, 1, 1, 1)
        self.rankA = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.rankA.setFont(font)
        self.rankA.setObjectName("rankA")
        self.gridLayout.addWidget(self.rankA, 10, 0, 1, 1)
        self.maxB = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.maxB.setFont(font)
        self.maxB.setObjectName("maxB")
        self.gridLayout.addWidget(self.maxB, 4, 1, 1, 1)
        self.subMatAB = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.subMatAB.setFont(font)
        self.subMatAB.setObjectName("subMatAB")
        self.gridLayout.addWidget(self.subMatAB, 2, 2, 1, 1)
        self.matBpowx = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.matBpowx.setFont(font)
        self.matBpowx.setObjectName("matBpowx")
        self.gridLayout.addWidget(self.matBpowx, 13, 2, 1, 1)
        self.traceB = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.traceB.setFont(font)
        self.traceB.setObjectName("traceB")
        self.gridLayout.addWidget(self.traceB, 8, 1, 1, 1)
        self.allB = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.allB.setFont(font)
        self.allB.setObjectName("allB")
        self.gridLayout.addWidget(self.allB, 0, 1, 1, 1)
        self.eigA = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.eigA.setFont(font)
        self.eigA.setObjectName("eigA")
        self.gridLayout.addWidget(self.eigA, 11, 0, 1, 1)
        self.matBmulx = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.matBmulx.setFont(font)
        self.matBmulx.setObjectName("matBmulx")
        self.gridLayout.addWidget(self.matBmulx, 11, 2, 1, 1)
        self.qrA = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.qrA.setFont(font)
        self.qrA.setObjectName("qrA")
        self.gridLayout.addWidget(self.qrA, 12, 0, 1, 1)
        self.svdA = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.svdA.setFont(font)
        self.svdA.setObjectName("svdA")
        self.gridLayout.addWidget(self.svdA, 15, 0, 1, 1)
        self.matA = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.matA.setFont(font)
        self.matA.setObjectName("matA")
        self.gridLayout.addWidget(self.matA, 1, 0, 1, 1)
        self.normA = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.normA.setFont(font)
        self.normA.setObjectName("normA")
        self.gridLayout.addWidget(self.normA, 6, 0, 1, 1)
        self.allA = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.allA.setFont(font)
        self.allA.setObjectName("allA")
        self.gridLayout.addWidget(self.allA, 0, 0, 1, 1)
        self.allAB = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.allAB.setFont(font)
        self.allAB.setObjectName("allAB")
        self.gridLayout.addWidget(self.allAB, 0, 2, 1, 1)
        self.cholA = QtWidgets.QPushButton(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.NoAntialias)
        self.cholA.setFont(font)
        self.cholA.setObjectName("cholA")
        self.gridLayout.addWidget(self.cholA, 14, 0, 1, 1)
        self.frame.raise_()
        self.horizontalLayoutWidget.raise_()
        self.groupBox_3.raise_()
        self.frame_2.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 890, 20))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/Images/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSave.setIcon(icon1)
        self.actionSave.setObjectName("actionSave")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/Images/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon2)
        self.actionOpen.setObjectName("actionOpen")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/Images/about.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon3)
        self.actionAbout.setObjectName("actionAbout")
        self.actionManual = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/Images/help.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionManual.setIcon(icon4)
        self.actionManual.setObjectName("actionManual")
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionOpen)
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionManual)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.precisionVal.setCurrentIndex(2)
        self.clearBtn.clicked.connect(self.resultsEntry.clear)
        self.actionSave.triggered.connect(self.saveBtn.click)
        self.actionAbout.triggered.connect(self.aboutBtn.click)
        self.actionManual.triggered.connect(self.manualBtn.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "BJ MATRIX CALCULATOR"))
        self.openBtn.setText(_translate("MainWindow", "Open"))
        self.saveBtn.setText(_translate("MainWindow", "Save"))
        self.clearBtn.setText(_translate("MainWindow", "Clear"))
        self.manualBtn.setText(_translate("MainWindow", "Manual"))
        self.aboutBtn.setText(_translate("MainWindow", "About"))
        self.groupBox_3.setTitle(_translate("MainWindow", "RESULTS"))
        self.resultsEntry.setToolTip(_translate("MainWindow", "Results Box"))
        self.groupBox_4.setTitle(_translate("MainWindow", "MATRIX A"))
        self.matAEntry.setToolTip(_translate("MainWindow", "Matrix A"))
        self.matAEntry.setPlainText(_translate("MainWindow", "1 0 0\n"
"0 1 0\n"
"0 0 1"))
        self.groupBox_5.setTitle(_translate("MainWindow", "MATRIX B"))
        self.matBEntry.setToolTip(_translate("MainWindow", "Matrix B"))
        self.matBEntry.setPlainText(_translate("MainWindow", "1 0 0\n"
"0 1 0\n"
"0 0 1"))
        self.swapBtn.setText(_translate("MainWindow", "SWAP"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Coef(x)"))
        self.x_val.setToolTip(_translate("MainWindow", "Coefficient of x"))
        self.x_val.setText(_translate("MainWindow", "1"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Precision"))
        self.precisionVal.setToolTip(_translate("MainWindow", "Precision of results"))
        self.precisionVal.setItemText(0, _translate("MainWindow", "1"))
        self.precisionVal.setItemText(1, _translate("MainWindow", "2"))
        self.precisionVal.setItemText(2, _translate("MainWindow", "3"))
        self.precisionVal.setItemText(3, _translate("MainWindow", "4"))
        self.precisionVal.setItemText(4, _translate("MainWindow", "5"))
        self.precisionVal.setItemText(5, _translate("MainWindow", "6"))
        self.precisionVal.setItemText(6, _translate("MainWindow", "7"))
        self.precisionVal.setItemText(7, _translate("MainWindow", "8"))
        self.precisionVal.setItemText(8, _translate("MainWindow", "9"))
        self.arrMulAB.setToolTip(_translate("MainWindow", "Matrix Multiplication"))
        self.arrMulAB.setText(_translate("MainWindow", "A.*B"))
        self.minB.setToolTip(_translate("MainWindow", "Minimum of Matrix B"))
        self.minB.setText(_translate("MainWindow", "Min(B)"))
        self.invA.setToolTip(_translate("MainWindow", "Matrix A inverse"))
        self.invA.setText(_translate("MainWindow", "A⁻¹"))
        self.detB.setToolTip(_translate("MainWindow", "Determinant of B"))
        self.detB.setText(_translate("MainWindow", "|B|"))
        self.addMatAB.setToolTip(_translate("MainWindow", "Matrix A plus Matrix B"))
        self.addMatAB.setText(_translate("MainWindow", "A+B"))
        self.arrdivmatAB.setToolTip(_translate("MainWindow", "Array Division"))
        self.arrdivmatAB.setText(_translate("MainWindow", "A./B"))
        self.luA.setToolTip(_translate("MainWindow", "LU factorization of A"))
        self.luA.setText(_translate("MainWindow", "LU(A)"))
        self.svdB.setToolTip(_translate("MainWindow", "singular-value Discomposition of B, B= USV"))
        self.svdB.setText(_translate("MainWindow", "SVD(B)"))
        self.cholB.setToolTip(_translate("MainWindow", "Cholesky factorization of B"))
        self.cholB.setText(_translate("MainWindow", "Chol(B)"))
        self.matApowx.setToolTip(_translate("MainWindow", "Matrix A power x"))
        self.matApowx.setText(_translate("MainWindow", "Aˣ"))
        self.logicalXOR.setToolTip(_translate("MainWindow", "Logical Exclusive OR; XOR"))
        self.logicalXOR.setText(_translate("MainWindow", "A#B"))
        self.rankB.setToolTip(_translate("MainWindow", "Rank of B"))
        self.rankB.setText(_translate("MainWindow", "Rank(B)"))
        self.luB.setToolTip(_translate("MainWindow", "LU factorization of B"))
        self.luB.setText(_translate("MainWindow", "LU(B)"))
        self.eigB.setToolTip(_translate("MainWindow", "Eigenvalues of B"))
        self.eigB.setText(_translate("MainWindow", "Eig(B)"))
        self.qrB.setToolTip(_translate("MainWindow", "Orthogonal-triangular decompositon; B=QR"))
        self.qrB.setText(_translate("MainWindow", "QR(B)"))
        self.autoBtn.setToolTip(_translate("MainWindow", "Compute all functions"))
        self.autoBtn.setText(_translate("MainWindow", "Auto"))
        self.matAmulx.setToolTip(_translate("MainWindow", "Matrix A multiply x"))
        self.matAmulx.setText(_translate("MainWindow", "A*x"))
        self.normB.setToolTip(_translate("MainWindow", "Norm of B"))
        self.normB.setText(_translate("MainWindow", "||B||₂"))
        self.logicalOR.setToolTip(_translate("MainWindow", "Element-wise logical OR"))
        self.logicalOR.setText(_translate("MainWindow", "A|B"))
        self.proAB.setToolTip(_translate("MainWindow", "Matrix Product"))
        self.proAB.setText(_translate("MainWindow", "A*B"))
        self.dimB.setToolTip(_translate("MainWindow", "Dimension of B"))
        self.dimB.setText(_translate("MainWindow", "Dim(B)"))
        self.logicalAND.setToolTip(_translate("MainWindow", "Element-wise logical AND"))
        self.logicalAND.setText(_translate("MainWindow", "A && B"))
        self.dimA.setToolTip(_translate("MainWindow", "Dimension of A"))
        self.dimA.setText(_translate("MainWindow", "Dim(A)"))
        self.invB.setToolTip(_translate("MainWindow", "Matrix B inverse"))
        self.invB.setText(_translate("MainWindow", "B⁻¹"))
        self.transA.setToolTip(_translate("MainWindow", "Matrix A transpose"))
        self.transA.setText(_translate("MainWindow", "Aᵀ"))
        self.maxA.setToolTip(_translate("MainWindow", "Maximun of Matrix A"))
        self.maxA.setText(_translate("MainWindow", "Max(A)"))
        self.traceA.setToolTip(_translate("MainWindow", "Trace of A"))
        self.traceA.setText(_translate("MainWindow", "Trace(A)"))
        self.detA.setToolTip(_translate("MainWindow", "Determinant of A"))
        self.detA.setText(_translate("MainWindow", "|A|"))
        self.minA.setToolTip(_translate("MainWindow", "Minimum of Matrix A"))
        self.minA.setText(_translate("MainWindow", "Min(A)"))
        self.matB.setToolTip(_translate("MainWindow", "Matrix B"))
        self.matB.setText(_translate("MainWindow", "B"))
        self.divmatAB.setToolTip(_translate("MainWindow", "Matrix Division"))
        self.divmatAB.setText(_translate("MainWindow", "A/B"))
        self.transB.setToolTip(_translate("MainWindow", "Matrix B Transpose"))
        self.transB.setText(_translate("MainWindow", "Bᵀ"))
        self.rankA.setToolTip(_translate("MainWindow", "Rank of A"))
        self.rankA.setText(_translate("MainWindow", "Rank(A)"))
        self.maxB.setToolTip(_translate("MainWindow", "Maximun of Matrix B"))
        self.maxB.setText(_translate("MainWindow", "Max(B)"))
        self.subMatAB.setToolTip(_translate("MainWindow", "Matrix A plus Matrix B"))
        self.subMatAB.setText(_translate("MainWindow", "A-B"))
        self.matBpowx.setToolTip(_translate("MainWindow", "Matrix B power x"))
        self.matBpowx.setText(_translate("MainWindow", "Bˣ"))
        self.traceB.setToolTip(_translate("MainWindow", "Trace of B"))
        self.traceB.setText(_translate("MainWindow", "Trace(B)"))
        self.allB.setText(_translate("MainWindow", "ALL B↓"))
        self.eigA.setToolTip(_translate("MainWindow", "Eigenvalues of A"))
        self.eigA.setText(_translate("MainWindow", "Eig(A)"))
        self.matBmulx.setToolTip(_translate("MainWindow", "Matrix B multiply  x"))
        self.matBmulx.setText(_translate("MainWindow", "B*x"))
        self.qrA.setToolTip(_translate("MainWindow", "Orthogonal-triangular decompositon; A=QR"))
        self.qrA.setText(_translate("MainWindow", "QR(A)"))
        self.svdA.setToolTip(_translate("MainWindow", "singular-value Discomposition of A, A= USV"))
        self.svdA.setText(_translate("MainWindow", "SVD(A)"))
        self.matA.setToolTip(_translate("MainWindow", "Matrix A"))
        self.matA.setText(_translate("MainWindow", "A"))
        self.normA.setToolTip(_translate("MainWindow", "Norm of A"))
        self.normA.setText(_translate("MainWindow", "||A||₂"))
        self.allA.setText(_translate("MainWindow", "ALL A ↓"))
        self.allAB.setText(_translate("MainWindow", "All AB ↓"))
        self.cholA.setToolTip(_translate("MainWindow", "Cholesky-Factorization of A"))
        self.cholA.setText(_translate("MainWindow", "Chol(A)"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionAbout.setShortcut(_translate("MainWindow", "Ctrl+B"))
        self.actionManual.setText(_translate("MainWindow", "Manual"))
        self.actionManual.setShortcut(_translate("MainWindow", "F1"))

import UI.icon_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

